site_name: Exploring myBCIT Essentials
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables

extra:
  generator: false

copyright: Copyright &copy 2024 - Ian Chan, Richard Maceda

extra_css:
  - stylesheets/extra.css
  - extra.css

nav:
  - index.md
  - task1.md
  - task2.md
  - task3.md
  - troubleshooting.md
  - glossary.md

theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.footer
  
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

