site_name: Ian Richard
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - index.md
  - task1.md
  - task2.md
  - task3.md
  - troubleshooting.md
  - glossary.md

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate